# Site settings
name: Sinead Naughton
email: sinead.m.naughton@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Java, Ruby, TypeScript, Angular, Spring, SQL, Web Design, Agile, "
skills: "I'm a full-stack software engineer. I love building great application, learning new technologies and skills, and solving problems."
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/sineadnaughton
  - title: github
    url: https://github.com/SineadNaughton
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
